### ISSUE TITLE
Increase font size

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#11]
I know you mentioned you dont want to add rich text to flashcards, but could you add an option to increase font size in the "settings" menu? It would be nice as it makes reading easier. Ideally it would be great to have an option for the upper card and one for the lower (otherwise if like me, you have more text on the lower one it could be problematic).

**Comment by tema6120** [comment]
You read my mind 😁. It's also in my todo-list. I plan to add item in general settings 'Card appearance', where you can adjust the font size, text alignment for question and answer. What else do you think can be added here?

**Comment by WPFilmmaker** [comment]
That's good :)

I was thinking if you implement subdecks maybe it could make sense to have cards tinted of different colors according to the types (for example red verbs, blu animals etc.) maybe it could help to memorize as it would tell you in which category a card is.

I am sure there are many useful options to be added but until I use the app and feel the need I can't think of more now :D

**Comment by tema6120** [comment]
Why am I against rich text? Because I encourage to keep cards simple. I think that excessive beautification of text is superfluous and it's not worth the time to spend on it. In my opinion, plain text is more than enough to make the card look understandable.

I'm going to use colors for lables but they will be displayed in the deck preview. I tend to think not to use colors other than white (or black in dark mode) for the background of the card. This way the user will be more focused on the questions. In addition, cards are colored light red if the card is expired due to the "Motivational Timer".

I am glad that you liked my video and will try to continue the series of videos to reveal all the features of the program.

**Comment by tema6120** [comment]
This is implemented in v1.6
<img src="https://user-images.githubusercontent.com/34657415/112143344-6c3ffc80-8be0-11eb-806a-60dd8a1e4dd4.png" height="640">
