### ISSUE TITLE
Add a donation page

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#14]
Since the app is so nice (IMHO it works better than stuff like duolinguo which has been downloaded million times) I think it makes sense (if you are interested) to have a donation page under 'help' in the 3 dots menu. If you don't accept donations in goods or money you can always specify that (like: I don't accept donations but you are welcome to contribute on github with feature request, translation and bug reports).

**Comment by tema6120** [comment]
Regarding donation, there are three concerns:
1. It's irrelevant yet because I have a small audience. At this point, I have only 5 active users on Google Play.
2. It seems none of popular donation service is available in my country (Ukraine).
3. Google Play [doesn't allow to receive donations](https://support.google.com/googleplay/android-developer/answer/9858738?hl=en&ref_topic=9857752). F-droid does.

As for translations and other things, yes, I'm going to move in that direction.

Thanks for the nice words about my app 😊

**Comment by WPFilmmaker** [comment]
@tema6120 I understand your points, so perhaps if/when you decide to accept donations you can add something on f-droid ;)
