### ISSUE TITLE
Ability to automatically swipe to the next card after clicking remember/not remember

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#26]
First of all thank you again for your work, I have been using ForgetMeNot for several days and it works amazingly. I tried to search for such function but I didn't find it so I think it doesn't exist.

When you click remember/not remember for cards you must swipe right to go to the next card. If you have decks with more than 20 cards (or multiple decks) after a while it gets a pain for the finger, and an unnecessary burden. I think it would be nice if once I click remember/not remember the app automatically moves to the next card.

**Comment by tema6120** [comment]
I reject because it's bad user experience. These buttons disclose an answer. Firstly, it takes some time just to read the answer. Secondly, It may be that the answer will be different from what a user originally thought and in this case the user will want to change the final answer (usually from 'Remember' to 'Not remember'). Thirdly, user might want to do another options with cards, for example, mark card as learned so that it won't be asked again. This way the exercise is more controllable.

And additionally I think you are exaggerating a little when you say that it gets a pain for the finger : )
