### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#28]
As a thank you to your great app, I would like to make a small contribution, the Italian translation. I am quite fluent in Italian, and while I am not familiar with translating jargon, I think I can make a decent work.

It is a small contribution from a non-dev but I think it could help non-english speaking users to try the app. Moreover one of the great aspect of FLOSS is inclusivity and a translated gui is always helpful.

How can I translate ForgetMeNot?

**Comment by tema6120** [comment]
I'm currently focusing on designing app and many text might be changed. After next release I will take care of translation. I'll let you know how to help translate later.

[This file](https://github.com/tema6120/ForgetMeNot/blob/master/app/src/main/res/values/strings.xml) needs to be translated but again, do not hurry to translate because the text can change a lot.

**Comment by WPFilmmaker** [comment]
Ok just let me know ;)

**Comment by tema6120** [comment]
Ok. I prepared for translation. I created a special article ['How to translate'](https://github.com/tema6120/ForgetMeNot/blob/master/.github/readme/HOW_TO_TRANSLATE.md).

**Comment by WPFilmmaker** [comment]
@tema6120 I saw the update and will update as soon as possible, I see many improvements! I will definitively use crowdin!
