### ISSUE TITLE
Two improvements for f-droid release

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#38]
1 The screenshot in the app are the ones from the previous version, since 1.2 introduced a lot of changes I think it is worth to update the screenshots.

2 Could you add a changelog of the changes of a new version? I think this is something developers decide and then f-droid scrapes automatically each time because I see some apps do and some apps don't...I think it is nice to see what changes before installing a new version.

**Comment by tema6120** [comment]
I updated the [fastlane structure](https://github.com/tema6120/ForgetMeNot/tree/master/fastlane/metadata/android/en-US) from where the data is retrieved for display on f-droid. But it seems I made a mistake. I updated after I tagged the release commit. With next release should be updated. By the way, the changelog has been updated as expected.

**Comment by WPFilmmaker** [comment]
by " By the way, the changelog has been updated as expected." do you mean that changelog was already added? Because I did not see it (maybe because I installed forgetmetnot from google play?).

**Comment by tema6120** [comment]
I just checked and my answer is YES. If you installed the app from Google Play changes are not displayed (maybe because the different signature). After unistalling the app I have 
![Screenshot_20210131-042141](https://user-images.githubusercontent.com/34657415/106372783-e2ac4500-637b-11eb-9a98-4691e042dc7f.png). Also changes are visible on the [site](https://f-droid.org/en/packages/com.odnovolov.forgetmenot/)
