### ISSUE TITLE
Feature request: Add sound cue when answering correctly Exercise Testing with Variants and Spellcheck

### ISSUE THREAD

**Issue by Xyde** [tema6120/ForgetMeNot#56]
This is something I really liked back in the days when using Memrise because it helped me study words better because it feels more seamless and there's less time dawning on the answer field so I get to press next faster. Since there's a vibration when the answer is wrong I think it would be feasible to make it choose between a sound cue too when we get it wrong.

**Comment by tema6120** [comment]
I don't like this idea. I believe that any application should not emit unnecessary sound effects unless there is a good reason. Especially in educational applications, because it can be distracting.

In addition, the exercise has the ability to automatically pronunciate the answer. In this case, it would certainly be inappropriate to mix sounds.
