### ISSUE TITLE
Bug? Design issue?: "No card is ready for exercise" for wrongly answered Spellcheck Exercise

### ISSUE THREAD

**Issue by Xyde** [tema6120/ForgetMeNot#57]
The Spellcheck feature is very cool, probably my favorite on this app (and makes me seriously consider switch from Anki) if not for this issue.

So I made a test deck, and put a Q/A in it. And purposely answered it wrong to see the outcome. What it does is that it creates an additional "card" so that I would have to go through it again. But what if I decide to leave the learning session because I ragequit? So I returned to the deck menu and saw that the card stats are being displayed as 0/1 learned. Ok, so after feeling less ragey I attempt to start the learning session again. However, it forces me to take an 8 h break because "no card is ready for exercise". 

![Screenshot_20210414_125232_com odnovolov forgetmenot](https://user-images.githubusercontent.com/7954447/114748987-74dbac80-9d20-11eb-8c17-4e0cf0529525.jpg)
![Screenshot_20210414_125234_com odnovolov forgetmenot](https://user-images.githubusercontent.com/7954447/114748999-77d69d00-9d20-11eb-9510-8dbf60afddb5.jpg)
![Screenshot_20210414_125245_com odnovolov forgetmenot](https://user-images.githubusercontent.com/7954447/114749064-8755e600-9d20-11eb-9f27-057f06f7f132.jpg)
![Screenshot_20210414_125248_com odnovolov forgetmenot](https://user-images.githubusercontent.com/7954447/114749073-8ae96d00-9d20-11eb-8f77-a31443ee97f0.jpg)
![Screenshot_20210414_125250_com odnovolov forgetmenot](https://user-images.githubusercontent.com/7954447/114749093-9046b780-9d20-11eb-974d-963a06f3b05c.jpg)
![Screenshot_20210414_125301_com odnovolov forgetmenot](https://user-images.githubusercontent.com/7954447/114749108-92a91180-9d20-11eb-9c78-ec818351ecd6.jpg)

Of course there is an option to turn off intervals. But I do like intervals. So my suggestion is to

Let us override the preexisting study session. Maybe delete the older data and replace it with new ones.

As for the deck putting cards into the "learnt stack" despite wrongly answering them, I suggest to implement some sort of regex check (this would be a new thread on its own) and check if the typed in answer matches the answer field. See below.

Feature request: add custom regex rules for Exercise Spellcheck
Say I have to answer a Q/A where strict spelling is not that important I think that a custom regex rule is nice to give leeway to frustrations caused by a capitalization issue or like an additional s/period lacking.

![Screenshot_20210414_125102_com odnovolov forgetmenot](https://user-images.githubusercontent.com/7954447/114750135-a43ee900-9d21-11eb-8dc2-4e63b7f92dc9.jpg)

**Comment by tema6120** [comment]
An exercise session should be seamless. This makes the intervals work as expected. I made exit dialog window on purpose to prevent accidental quitting.

In terms of my app, 'Learned card' means the card will never be asked in exercise. This is the same as the card would be removed but the difference is that it is simply stored. You can listen to it on the player or return it back to the exercise if you decide to study it again.

By default, if you ask wrong the card will be duplicated to the end of the card list. But you can change this behavior. Just go to deck settings -> Grading -> set 'No' below the answer 'Ask again?'.

If something goes wrong with the grade (for example, you think the answer is correct but the app counted as wrong) you can change the grade manually which in turn will determine the interval that is right for you.

About rules for checking. Using regex will be too compicated to the user. I myself do not quite understand how regex can be used in order to specify the validation rules. About capitalization issue: I made an error. I was sure that the check happens ignoring case. This will certainly be fixed.

**Comment by tema6120** [comment]
Since 1.8.1 spell checking is performed ignoring case
